Feature/16 optional invite language for users
IxorTalk/ixortalk-organization-api pull request #17
Opened 2020-08-21 06:53 UTC by steinmaerivoet

2020-08-21 09:18 UTC, wjans requested changes

2020-08-21 09:18 UTC, wjans commented on src/main/java/com/ixortalk/organization/api/domain/User.java
> +    public void setInviteLanguage(String inviteLanguage) {
Don't expose setters

2020-08-21 09:18 UTC, wjans commented on src/main/java/com/ixortalk/organization/api/error/GenericExceptionHandler.java
> +        for (FieldError fieldError : e.getErrors().getFieldErrors()) {
Would you mind refactoring this in streaming flavor?

2020-08-21 09:18 UTC, wjans commented on src/main/java/com/ixortalk/organization/api/error/GenericExceptionHandler.java
> +    public static class ErrorReport {
Rather move these classes to upper level instead of nested class

2020-08-21 09:18 UTC, wjans commented on src/main/java/com/ixortalk/organization/api/mail/InviteUserService.java
> +                Optional.ofNullable(user.getInviteLanguage()).orElse(ixorTalkConfigProperties.getOrganization().getApi().getMail().getDefaultMailLanguageTag()),
Use static imports where possible, and maybe expose invite language as optional on domain entity itself? (json ignored)

2020-08-21 09:18 UTC, wjans commented on src/test/java/com/ixortalk/organization/api/service/InviteUserServiceIntegrationTest.java
> +/**
We always write end-to-end integration tests on REST calls, below functionality should be tested there too.  Case with fallback to configured default should already be present? Just add a second one with an invite language specified.

2020-08-21 09:18 UTC, wjans commented on src/test/java/com/ixortalk/organization/api/service/InviteUserServiceIntegrationTest.java
> +/**
And don't forget the resent invite :-)

2020-08-21 09:18 UTC, wjans commented on src/test/java/com/ixortalk/organization/api/rest/OrganizationRestResource_AddUserInOrganization_IntegrationAndRestDocTest.java
> +                                                fieldWithPath("login").type(STRING).description("The `login` (email address) for the user to add"),
Mark as being optional

2020-08-21 09:18 UTC, wjans commented on src/main/asciidoc/index.adoc
>  REST call to be made when users are actually being used.  This call will trigger an invite for created (status `CREATED`) users.
Request fields are not included in adoc when adding users, although it gets generated, can you include them?  Your restdocs test changes are not visible now. (this is an existing "issue")

2020-08-21 12:36 UTC, steinmaerivoet commented on src/test/java/com/ixortalk/organization/api/rest/OrganizationRestResource_AddUserInOrganization_IntegrationAndRestDocTest.java
> +                                                fieldWithPath("login").type(STRING).description("The `login` (email address) for the user to add"),
The optional identifier was added to the requestfield after the description. I also added the optional identifier to the description.

2020-08-25 07:28 UTC, wjans commented on src/test/java/com/ixortalk/organization/api/domain/UserTestBuilder.java
> +    private String inviteLanguage = "nl";
Our approach in using test builders is providing default values for required fields and leaving optional fields empty, so this one should remain empty by default.

2020-08-25 07:31 UTC, wjans commented on src/test/java/com/ixortalk/organization/api/rest/OrganizationRestController_UsersUsed_IntegrationAndRestDocTest.java
> +    public void asAdminForUserWithInviteLanguageNl() throws JsonProcessingException {
Explicitly set the value to test as custom invite language here.

2020-08-25 07:35 UTC, wjans commented on src/test/java/com/ixortalk/organization/api/service/InviteUserServiceIntegrationTest.java
> +/**
This test should be removed now.

2020-09-03 12:34 UTC, wjans commented on src/test/java/com/ixortalk/organization/api/rest/OrganizationRestController_UsersUsed_IntegrationAndRestDocTest.java
> +        mailingServiceWireMockRule.verify(1, postRequestedFor(urlEqualTo("/mailing/send")).withRequestBody(containing("\"languageTag\":\"nl\"")));
This is not correctly tested, `inviteLanguage` gets set to `en` explicitly in this test but the verify happens with `nl`?

2020-09-03 12:36 UTC, wjans commented on src/test/java/com/ixortalk/organization/api/rest/UserRestController_ResendInvite_IntegrationAndRestDocTest.java
> +    public void organizationAdminResendInviteForUserWithInviteLanguageNl() throws JsonProcessingException {
Test name is not correct according to what is tested (`nl` vs. `en`).  Also remove exception that is not being thrown.

2020-09-04 05:01 UTC, wjans approved these changes

2020-09-04 05:02 UTC, merged